name: Build SwiftShader

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Clean up previous Python installations to avoid conflicts
      - name: Remove previous Python installations
        run: |
          if (Test-Path 'C:\Python313') { Remove-Item -Recurse -Force 'C:\Python313' }
          if (Test-Path 'C:\Program Files\Python*') { Remove-Item -Recurse -Force 'C:\Program Files\Python*' }
          if (Test-Path 'C:\Users\RunnerUser\AppData\Local\Programs\Python') { Remove-Item -Recurse -Force 'C:\Users\RunnerUser\AppData\Local\Programs\Python' }
        shell: powershell

      # Install Python using PowerShell
      - name: Install Python 3.8
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe -OutFile python-installer.exe
          Start-Process -Wait -FilePath python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1"
        shell: powershell

      - name: Install Dependencies (via Chocolatey)
        run: |
          choco install cmake ninja python3 -y
        shell: powershell

      - name: Install Visual Studio Build Tools (MSVC)
        run: |
          choco install visualstudio2019buildtools -y
        shell: powershell

      - name: Run build.cmd
        run: .\swiftshader-dist-win-1.0.7.4\buildscript\build.cmd
        shell: powershell

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: SwiftShader-Binaries
          path: build/  # Adjust this path to match where the binaries are output
